version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        environment: 
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "15672:15672"
            - "5672:5672" 

    bot:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on: 
            - rabbitmq